name: Test

on: [pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src --level max