#name: PHP CI
#on: [push, pull_request]
#jobs:
#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: PHPStan
#        uses: docker://oskarstark/phpstan-ga
#        with:
#          args: analyse src/
on: [push, pull_request]
name: Test
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          secrets: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: analyse src --level max